#pragma once
#include "Building.h"

class Player;
enum class ResourceType;

/**
 * @file Settlement.h
 * @brief Defines the Settlement class, representing a settlement in the game.
 */

/**
 * @class Settlement
 * @brief Represents a settlement built by a player in the game.
 * 
 * The `Settlement` class inherits from the `Building` class and represents a settlement that
 * a player can build on the game board. Each settlement is owned by a player and is associated
 * with a specific color representing the player. Settlements can generate resources based on the
 * surrounding hex tiles, and they play a critical role in the development and expansion of the player.
 */
class Settlement : public Building {
public:
    /**
     * @brief Constructs a Settlement object for a player.
     * @param owner The player who owns this settlement.
     * @param color The color associated with the player who owns the settlement.
     */
    Settlement(Player* owner, sf::Color color);

    /**
     * @brief Adds a resource to the player's inventory.
     * 
     * This method is responsible for adding a resource to the player's inventory, based on
     * the type of resource generated by the terrain surrounding the settlement.
     * 
     * @param type The type of resource to be added to the player's inventory.
     */
    virtual void addResource(ResourceType type);
};
